--- !TronConfiguration

nodes:
    - &nodeBatch00 !Node
        hostname: batch0
    - &nodeBatch01 !Node
        hostname: batch1
    - &nodeBatch02 !Node
        hostname: batch2
    
resources:
    - &resourceNode01 !NodeResource
        # For this resource to 'available', the node must be accessible, and the defined limits must be met.
        node: *nodeBatch01
        limit_load: 2.0
        limit_disk_space: 
            path: /nail
            size: 10GB

    - &resourceFile01 !FileResource
        # A resource indicating a specific feature on the file system.
        path: /nail/live/yelp/logs/foo.log.gz
        age: 2hrs
        size: 0
    
jobs:
    - &jobFoo !BatchJob
        name: "Foo Job"
        path: "$BATCH_DIR/foo.py"
        args: "--test"
        schedule: !IntervalScheduler
            interval: 1hr
        runtime_warning: 30min
        runtime_fail: 45min
        dependencies:
            - *resourceNode01
            - *resourceFile01

    - &jobBar !BatchJob
        name: "Bar Job"
        path: "$BATCH_DIR/bar.py"
        schedule: !DailyScheduler
            days: [Mon, Tue, Wed]
            time_after: 08:00:00
        dependencies:
            - !JobResource
                job: *jobFoo
                last_success: 2hrs
            